name: Generate Snake

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: suchetkumbar
          outputs: dist/snake.svg
      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generated snake animation"
